version: '3'

services:
    main:
        build:
            context: .
            dockerfile: ../dockerfiles/dev.Dockerfile
        
        init: true
        volumes:
            - ..:/learn-mikanos:cached
            - /tmp/.X11-unix:/tmp/.X11-unix:consistent
        
        tty: true
        user: vscode