name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    name: Build all chapters
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build all chapters
        uses: ./.github/actions/build-all-chapters
      
